apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordercheckout
spec:
  selector:
    matchLabels:
      app: ordercheckout

  template:
    metadata:
      labels:
        app: ordercheckout
    spec:
      containers:
        - name: ordercheckout
          image: bosamatheus/ecommerce-microservice-order
          command: ["./order"]
          args: ["-opt", "checkout"]
          ports:
            - containerPort: 6572
          env:
            - name: PRODUCT_URL
              value: "http://product-service:8082"
            - name: RABBITMQ_ERLANG_COOKIE
              value: "SWQOKODSQALRPCLNMEQG"
            - name: RABBITMQ_DEFAULT_USER
              value: "rabbitmq"
            - name: RABBITMQ_DEFAULT_PASS
              value: "rabbitmq"
            - name: RABBITMQ_DEFAULT_VHOST
              value: "/"
            - name: RABBITMQ_DEFAULT_HOST
              value: "rabbitmq-service"
            - name: REDIS_HOST
              value: "redis-service:6379"

---

apiVersion: v1
kind: Service
metadata:
  name: ordercheckout-service
  labels:
    app: ordercheckout-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6572
  selector:
    app: ordercheckout
